[package]
name = "day-8-rust"
version = "0.1.0"
authors = ["Aaron Choo <choozy.aaron@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
